# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "StoreFlowtest"
client_id = "62f7f03d15494b82a6a4be06578c0993"
application_url = "https://shelfflow.onrender.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products,read_inventory,write_inventory,read_locations"
optional_scopes = [ ]
use_legacy_install_flow = false

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

[auth]
redirect_urls = [
  "https://shelfflow.onrender.com/auth/callback",
  "https://shelfflow.onrender.com/auth/shopify/callback",
  "https://shelfflow.onrender.com/api/auth/callback"
]
